# Usign the Clean Blog theme

title: Objectif Agrégation
email: objectif-agregation@h-k.fr
description: Site web du livre Objectif Agrégation
baseurl: ""
url: "http://objectifagregation.github.io"
github_username:  objectifagregation

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["node_modules"]
